-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 08:10:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`food company supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food company supplier` (
  `id` INT NOT NULL,
  `companyname` VARCHAR(45) NOT NULL,
  `companyinsurance` VARCHAR(45) NOT NULL,
  `companycontactno` VARCHAR(45) NOT NULL,
  `companyaddress` VARCHAR(45) NOT NULL,
  `store branch manager_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food supplies` (
  `id` INT NOT NULL,
  `stock_burger` INT NOT NULL,
  `stock_burgerpatty` INT NOT NULL,
  `stock_popcorn` INT NOT NULL,
  `stock_sandwich` INT NOT NULL,
  `stock_junkfoods` INT NOT NULL,
  `stock_softdrink` INT NOT NULL,
  `store branch manager_id` INT NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_food supplies_companyname`
    FOREIGN KEY ()
    REFERENCES `mydb`.`food company supplier` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
