-- MySQL Script generated by MySQL Workbench
-- 10/14/19 09:00:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`store branch manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store branch manager` (
  `id` INT NOT NULL COMMENT '',
  `sbfirstname` VARCHAR(45) NOT NULL COMMENT '',
  `sbsurname` VARCHAR(45) NOT NULL COMMENT '',
  `sbbday` DATE NOT NULL COMMENT '',
  `sbage` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food company supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food company supplier` (
  `id` INT NOT NULL COMMENT '',
  `companyname` VARCHAR(45) NOT NULL COMMENT '',
  `companyinsurance` VARCHAR(45) NOT NULL COMMENT '',
  `companycontactno` VARCHAR(45) NOT NULL COMMENT '',
  `companyaddress` VARCHAR(45) NOT NULL COMMENT '',
  `store branch manager_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `store branch manager_id`)  COMMENT '',
  INDEX `fk_food company supplier_store branch manager1_idx` (`store branch manager_id` ASC)  COMMENT '',
  CONSTRAINT `fk_food company supplier_store branch manager1`
    FOREIGN KEY (`store branch manager_id`)
    REFERENCES `mydb`.`store branch manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `id` INT NOT NULL COMMENT '',
  `branchaddress` VARCHAR(45) NOT NULL COMMENT '',
  `food company supplier_id` INT NOT NULL COMMENT '',
  `food company supplier_store branch manager_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `food company supplier_id`, `food company supplier_store branch manager_id`)  COMMENT '',
  INDEX `fk_branch_food company supplier1_idx` (`food company supplier_id` ASC, `food company supplier_store branch manager_id` ASC)  COMMENT '',
  CONSTRAINT `fk_branch_food company supplier1`
    FOREIGN KEY (`food company supplier_id` , `food company supplier_store branch manager_id`)
    REFERENCES `mydb`.`food company supplier` (`id` , `store branch manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL COMMENT '',
  `employeetype` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventory` (
  `id` INT NOT NULL COMMENT '',
  `foodstockitems` INT NULL COMMENT '',
  `drinkstockitems` INT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `employee_id`)  COMMENT '',
  INDEX `fk_inventory_employee1_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_inventory_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food supplies` (
  `id` INT NOT NULL COMMENT '',
  `stock_burger` INT NOT NULL COMMENT '',
  `stock_burgerpatty` INT NOT NULL COMMENT '',
  `stock_popcorn` INT NOT NULL COMMENT '',
  `stock_sandwich` INT NOT NULL COMMENT '',
  `stock_junkfoods` INT NOT NULL COMMENT '',
  `stock_softdrink` INT NOT NULL COMMENT '',
  `store branch manager_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `store branch manager_id`)  COMMENT '',
  INDEX `fk_food supplies_store branch manager1_idx` (`store branch manager_id` ASC)  COMMENT '',
  CONSTRAINT `fk_food supplies_store branch manager1`
    FOREIGN KEY (`store branch manager_id`)
    REFERENCES `mydb`.`store branch manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deliver receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deliver receipts` (
  `id` INT NOT NULL COMMENT '',
  `companyname` VARCHAR(45) NOT NULL COMMENT '',
  `companycontactno` VARCHAR(45) NOT NULL COMMENT '',
  `companyaddress` VARCHAR(45) NOT NULL COMMENT '',
  `dateoforder` DATE NOT NULL COMMENT '',
  `` VARCHAR(45) NULL COMMENT '',
  `store branch manager_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `store branch manager_id`)  COMMENT '',
  INDEX `fk_deliver receipts_store branch manager1_idx` (`store branch manager_id` ASC)  COMMENT '',
  CONSTRAINT `fk_deliver receipts_store branch manager1`
    FOREIGN KEY (`store branch manager_id`)
    REFERENCES `mydb`.`store branch manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
